version: "3.4"

services:
  mongo:
    container_name: venue_mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=Venue
  web:
    container_name: venue_web
    build: ./
    command: npm run serve
    restart: unless-stopped
    volumes:
      - ./:/app
      - web_node_modules:/app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
      - server
  server:
    container_name: venue_server
    build: ./server
    command: ./node_modules/.bin/nodemon server
    restart: unless-stopped
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017/Venue
      - AWSSecretKey=${AWSSecretKey}
      - AWSAccessKeyId=${AWSAccessKeyId}
      - WEBEX_CLIENT_SECRET=${WEBEX_CLIENT_SECRET}
      - WEBEX_CLIENT_ID=${WEBEX_CLIENT_ID}
      - EMAIL_PASS=${EMAIL_PASS}
      - AUTH_KEY=${AUTH_KEY}
    depends_on:
      - mongo

volumes:
  mongo_data:
  web_node_modules:
  server_node_modules:
